practice_django/app1/urls.py
from django.urls import include, path

from . import views

app_name = "app1"


def task_dispatcher(request, semester_number, task_name):
    if task_name == 'form':
        view_class = views.TaskFormView.as_view()
    else:
        view_class = views.TaskView.as_view()

    return view_class(request, semester_number=semester_number, task_name=task_name)


urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('semester/<int:semester_number>/', views.SemesterView.as_view(), name="semester"),
    path('semester/<int:semester_number>/task/<str:task_name>/', task_dispatcher, name="task"),
    path('jquery_test/', views.JqueryTestView.as_view(), name="jquery_test")
]

practice_django/home/urls.py
from django.urls import include, path, reverse, NoReverseMatch
from django.apps import apps
from django.shortcuts import redirect

from . import views

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

practice_django/practice_django/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import static
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('app1/', include('app1.urls')),
    path('account/', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# нельзя так делать при серьезном проекте
# for app in apps.get_app_configs():
#     app_name = app.name
#     if app_name != "home" and "django" not in app_name:
#         urlpatterns.append(
#             path(f'{app_name}/', include(f'{app_name}.urls'))
#         )
#
#     # try:
#     #     reverse(f"{app_name}")
#     #     app_names.append(app_name)
#     # except NoReverseMatch:
#     #     continue

practice_django/app1/models.py
from django.db import models
from django.conf import settings


class ProgLang(models.Model):
    prog_lang_name = models.CharField(max_length=64)

    def __str__(self):
        return self.prog_lang_name


class Application(models.Model):
    fio = models.CharField(max_length=255)
    telephone = models.CharField(max_length=20)
    email = models.EmailField(max_length=255)
    bday = models.DateField()
    sex = models.CharField(max_length=5)
    biography = models.TextField(max_length=512, blank=True)
    prog_langs = models.ManyToManyField(ProgLang)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return (f"fio: {self.fio}, telephone: {self.telephone}, email: {self.bday},"
                f" sex: {self.sex}, biography: {self.fio}, prog_langs: {self.prog_langs}")

practice_django/app1/forms.py
from django import forms
from django.core.exceptions import ValidationError
from datetime import date
import re

from .models import Application, ProgLang


class ApplicationModelForm(forms.ModelForm):
    prog_langs = forms.ModelMultipleChoiceField(
        queryset=ProgLang.objects.all(),
        widget=forms.SelectMultiple,
        label="Любимый язык программирования"
    )

    class Meta:
        model = Application
        fields = ['fio', 'telephone', 'email', 'bday', 'sex', 'prog_langs', 'biography']
        widgets = {
            'sex': forms.RadioSelect(choices=[('man', 'Мужской'), ('woman', 'Женский')]),
            'bday': forms.DateInput(attrs={'type': 'date'}),
        }
        labels = {
            'fio': 'ФИО',
            'telephone': 'Телефон',
            'email': 'Email',
            'bday': 'Дата рождения',
            'biography': 'Биография',
            'prog_langs': 'Любимый язык программирования',
            'sex': 'Пол',
        }

    def __init__(self, *args, **kwargs):
        super(ApplicationModelForm, self).__init__(*args, **kwargs)
        self.fields['prog_langs'].help_text = ''

    def clean_fio(self):
        re_pattern = r'^[\w\sА-Яа-яЁё]+$'
        fio = self.cleaned_data.get('fio').strip()
        if not re.fullmatch(re_pattern, fio):
            raise ValidationError(
                'Fio have only letters',
                code='invalid fio'
            )
        return fio

    def clean_telephone(self):
        re_pattern = r'^(\s*)?(\+)?([- _():=+]?\d[- _():=+]?){10,14}(\s*)?$'
        telephone = self.cleaned_data.get('telephone').strip()
        if not re.fullmatch(re_pattern, telephone):
            raise ValidationError(
                'Telephone have only digits and +, 10 <= digits <= 14',
                code='invalid telephone'
            )
        return telephone

    def clean_email(self):
        re_pattern = r'^[\w\-\.]+@([\w-]+\.)+[\w-]{2,4}$'
        email = self.cleaned_data.get('email').strip()
        if not re.fullmatch(re_pattern, email):
            raise ValidationError(
                'Invalid email',
                code='invalid email'
            )
        return email

    def clean_bday(self):
        bday = self.cleaned_data.get('bday')
        if not (date(year=1900, month=1, day=1) <= bday <= date.today()):
            raise ValidationError(
                'Invalid birthday',
                code='invalid bday'
            )
        return bday

    def clean_sex(self):
        sex = self.cleaned_data.get('sex').strip()
        if sex not in ('man', 'woman'):
            raise ValidationError(
                'Invalid sex',
                code='invalid sex'
            )
        return sex

practice_django/app1/views.py
from django.shortcuts import render, reverse, NoReverseMatch
from django.http import HttpResponse, Http404
from django.template.loader import get_template, TemplateDoesNotExist
from django.views.generic import TemplateView, FormView, UpdateView
from django.views.generic.base import ContextMixin
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .forms import ApplicationModelForm
from .models import Application


# Create your views here.
class IndexView(TemplateView):
    template_name = 'app1/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['semester_numbers'] = [3, 4]
        return context


class JqueryTestView(TemplateView):
    template_name = 'app1/jquery_test.html'


class SemesterView(TemplateView):
    template_name = 'app1/semester.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        semester_number = self.kwargs.get('semester_number')
        if semester_number == 3:
            context['semester_number'] = semester_number
            context['tasks'] = [
                {
                    'name': f'Задание {task_name}',
                    'url': reverse('app1:task',
                                   kwargs={"semester_number": semester_number,
                                           "task_name": task_name}
                                   )
                }
                for task_name in range(1, 9)
            ]

        elif semester_number == 4:
            context['semester_number'] = semester_number
            context['tasks'] = [
                {
                    'name': 'form',
                    'url': reverse('app1:task',
                                   kwargs={"semester_number": 4,
                                           "task_name": 'form'}
                                   )
                }
            ]

        else:
            raise Http404("Нет семестра с таким номером")

        return context


class TaskView(TemplateView):
    def get_template_names(self):
        semester_number = self.kwargs.get('semester_number')
        task_name = self.kwargs.get('task_name')
        template_name = f"app1/sem{semester_number}/task_{task_name}.html"
        try:
            return get_template(template_name)
        except TemplateDoesNotExist:
            raise Http404("Нет такой задачи")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        semester_number = self.kwargs.get('semester_number')
        task_name = self.kwargs.get('task_name')
        context['semester_number'] = semester_number
        context['task_name'] = task_name
        if task_name == "7":
            context["jpg_names"] = [f'app1/media/sem3/{i}.jpg' for i in range(1, 9)]
        return context


class TaskFormView(LoginRequiredMixin, UpdateView):
    template_name = 'app1/sem4/task_form.html'
    form_class = ApplicationModelForm
    model = Application
    login_url = 'account:sign_up'
    success_url = reverse_lazy('app1:task', kwargs={'semester_number': 4, 'task_name': 'form'})
    extra_context = {
        'semester_number': 4,
        'task_name': 'form'
    }

    def get_object(self, queryset=None):
        try:
            return self.model.objects.get(user=self.request.user)
        except self.model.DoesNotExist:
            return self.model(user=self.request.user)

    def form_valid(self, form):
        application = form.save(commit=False)
        application.user = self.request.user
        # application.save()
        messages.success(self.request, 'Данные успешно сохранены, спасибо!')
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)

practice_django/app1/templates/app1/base_task.html
{% extends 'base.html' %}

{% load static %}

{% block aside %}
    <nav class="aside-link">
        <a href="{% url "app1:index" %}"  class="">Выбор семестра</a>
    </nav>
    <nav class="aside-link">
        <a href="{% url 'app1:semester' semester_number %}"  class="">Выбор задания семестра</a>
    </nav>
{% endblock %}

practice_django/app1/templates/app1/index.html
{% extends 'base.html' %}

{% load static %}

{% block page_title %}
    Список семестров
{% endblock %}

{% block header_title %}
    Список семестров
{% endblock %}

{% block aside %}
    <nav class="aside-link">
        <a href="{% url 'app1:jquery_test' %}">Тест Jquery</a>
    </nav>
{% endblock %}

{% block content %}
    <div class="tasks">
        <h1>Семестры:</h1>
        <div class="tasks-list">
            {% for semester_number in semester_numbers %}
                <a class="link-to-task"
                   href="{% url 'app1:semester' semester_number %}"
                >Семестр {{ semester_number }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

practice_django/app1/templates/app1/jquery_test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<script src="{% static 'app1/js/sem3/jquery.js' %}" defer></script>
	<script src="{% static 'app1/js/sem3/jquery_test.js' %}" defer></script>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'app1/css/sem3/jquery_test.css' %}">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">
	<title>Тест Jquery</title>
</head>

<body>
<header>
	<nav class="header-logo">
		<img class="header-logo" src="{% static 'media/logo.png' %}" alt="Logo">
	</nav>
	<nav class="header-info">
		<h2 class="black header-title">$$$ website?</h2>
		<h3 class="black header-task">Тест Jquery</h3>
	</nav>

</header>

<aside>
	<nav class="aside-link">
		<a href="{% url 'home:home' %}"  class="black">Главная страница</a>
	</nav>
    <nav class="aside-link">
        <a href="{% url 'app1:index' %}" class="">Выбор семестра</a>
    </nav>
</aside>

<main>
	<div id="divs">
		<div class="div_anim" id="d1">
			<h1 class="black">1</h1>
		</div>
		<div class="div_anim" id="d2">
			<h1 class="black">2</h1>
		</div>
		<div class="div_anim" id="d3">
			<h1 class="black">3</h1>
		</div>
		<div class="div_anim" id="d4">
			<h1 class="black">4</h1>
		</div>
	</div>
	<h1 id="bye">Бай бай</h1>
	<div class="div_button" id="stop_button">Остановить анимации</div>
	<div class="div_button" id="add_button">Добавить контент</div>
	<div class="div_button" id="del_button">Удалить контент</div>
	<div id="h1_ajax">
		<h1>Здесь будет текст из test_ajax.txt</h1>
	</div>
</main>

<footer>
	<p class="black text_in_footer">created by</p>
	<h3 class="black text_in_footer">Денис Чупилко</h3>
</footer>
</body>
</html>

practice_django/app1/templates/app1/semester.html
{% extends 'base.html' %}

{% load static %}

{% block page_title %}
    Задания {{ semester_number }} семестра
{% endblock %}

{% block header_title %}
    Задания {{ semester_number }} семестра
{% endblock %}

{% block aside %}
    <nav class="aside-link">
        <a href="{% url 'app1:index' %}" class="">Выбор семестра</a>
    </nav>
{% endblock %}

{% block content %}
    <div class="tasks">
        <h1>Задания:</h1>
        <div class="tasks-list">
            {% for task in tasks %}
                <a class="link-to-task" href="{{ task.url }}">
                    {{ task.name }}
                </a>
            {% endfor %}
{#            {% for task_number in task_numbers %}#}
{#                <a class="link-to-task" href=#}
{#                        "{% url 'app1:task' semester_number=semester_number task_number=task_number %}"#}
{#                >Задание {{ task_number }}</a>#}
{#            {% endfor %}#}
        </div>
    </div>
{% endblock %}