practice_django/account/urls.py
from django.apps import AppConfig
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path('', views.ProfileView.as_view(), name='profile'),
    path('profile_edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in/', views.SignInView.as_view(), name='sign_in'),
    path('log_out/', views.CustomLogOutView.as_view(), name='log_out'),
]

practice_django/app1/urls.py
from django.urls import include, path

from . import views

app_name = "app1"


def task_dispatcher(request, semester_number, task_name):
    if task_name == 'form':
        view_class = views.TaskFormView.as_view()
    else:
        view_class = views.TaskView.as_view()

    return view_class(request, semester_number=semester_number, task_name=task_name)


urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('semester/<int:semester_number>/', views.SemesterView.as_view(), name="semester"),
    path('semester/<int:semester_number>/task/<str:task_name>/', task_dispatcher, name="task"),
    path('jquery_test/', views.JqueryTestView.as_view(), name="jquery_test")
]

practice_django/home/urls.py
from django.urls import include, path, reverse, NoReverseMatch
from django.apps import apps
from django.shortcuts import redirect

from . import views

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

practice_django/practice_django/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import static
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('app1/', include('app1.urls')),
    path('account/', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# нельзя так делать при серьезном проекте
# for app in apps.get_app_configs():
#     app_name = app.name
#     if app_name != "home" and "django" not in app_name:
#         urlpatterns.append(
#             path(f'{app_name}/', include(f'{app_name}.urls'))
#         )
#
#     # try:
#     #     reverse(f"{app_name}")
#     #     app_names.append(app_name)
#     # except NoReverseMatch:
#     #     continue

practice_django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100;200;300;400;500;600;700;800&display=swap"
          rel="stylesheet">
    {% block extra_links %}
    {% endblock %}
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
</head>

<body>
{% block extra_body %}

{% endblock %}
<header>
    <nav class="logo-nav">
        <img class="header-logo" src="{% static 'media/logo.png' %}" alt="Logo">
    </nav>
    <nav class="header-info">
        <h2 class="header-title">$$$ website?</h2>
        <h3 class="header-task">
            {% block header_title %}
                {#                    В дочернем классе здесь будет название страницы#}
            {% endblock %}
        </h3>
    </nav>
</header>

<aside>
    <nav class="aside-link">
        <a href="{% url 'home:home' %}" class="">Главная страница</a>
    </nav>
    <nav class="aside-link">
        <a href="{% url 'account:profile' %}" class="">Профиль</a>
    </nav>
    {% if user.is_superuser %}
        <nav class="aside-link">
            <a href="{% url 'admin:index' %}" class="">Админ-панель</a>
        </nav>
    {% endif %}
    {% block aside %}
        {#                    В дочернем классе здесь ссылки aside страницы#}
    {% endblock %}
</aside>

<main>
    {% block content %}
        {#            В дочернем шаблоне здесь будет сама задача#}
    {% endblock %}
</main>

<footer>
    <p class="text_in_footer">created by</p>
    <h3 class="text_in_footer">Денис Чупилко</h3>
</footer>
</body>

</html>